spring.application.name=backend_med

# ----------------- Configuration de la base de données -----------------
spring.datasource.url=jdbc:mysql://localhost:3306/dbs_prmed?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ----------------- JPA / Hibernate -----------------

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Africa/Casablanca


# ----------------- Autres -----------------
server.port=8080


# ===== Configuration email Gmail =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hichamakil2018@gmail.com
spring.mail.password=kilblqpvvrugciwq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

huggingface.api.token=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
huggingface.api.url=https://api-inference.huggingface.co/models
huggingface.api.model=HuggingFaceTB/SmolLM2-1.7B-Instruct

jwt.secret=myVerySecureAndLongSecretKeyThatIsAtLeast32CharactersLong123456
jwt.expiration=3600000

cloudinary.cloud.name=dt7p1pmqy
cloudinary.api.key=187295877211971
cloudinary.api.secret=c2A_k0vvgN1buk2qtmVharcoXoE


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
